### ISSUE TITLE
i cant load the weight .h5 file given in weight/mobilenetv2/ folder, while runnig evaluate.py file with --dbname='utkface' and --model= 'mobilenetv2'

### ISSUE THREAD

**Issue by gulatisimran** [dandynaufaldi/Agendernet#2]

**Comment by dandynaufaldi** [comment]
Can you give the detail in error message and what is the name for utkface dataset folder in your computer?

**Comment by dandynaufaldi** [comment]
@gulatisimran  should be fixed in commit [1](https://github.com/dandynaufaldi/Agendernet/commit/9f45870e8a144f4f0192e85459a53249aae0ff44) , [2](https://github.com/dandynaufaldi/Agendernet/commit/e9c5d256cc78c393647623a9c85929887b02619c), and [3](https://github.com/dandynaufaldi/Agendernet/commit/d9746329e574bdfa6018f2aec1b9f9caa84f246b)
